server.port: 9999
facebook:
  client:
    clientId: 233668646673605
    clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me
    
github:
  client:
    clientId: bd1c0a783ccdd1c9b9e4
    clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user
    
weibo:
  client:
    clientId: bd1c0a783ccdd1c9b9e4
    clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
    accessTokenUri: https://api.weibo.com/oauth2/access_token
    userAuthorizationUri: https://open.weibo.cn/oauth2/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user
    
userinfo:
  userlist:
   - username: user1
     password: $2a$12$gFQu4iYq9iwuVqJgT3hIxedLbgdhztXSYlqYKFJgVmcEJ5XNeciZy
     role: admin
   - username: user2
     password: $2a$12$gFQu4iYq9iwuVqJgT3hIxedLbgdhztXSYlqYKFJgVmcEJ5XNeciZy
     role: developer
 
spring:
  datasource.url: jdbc:mysql://localhost:3306/myBlog?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8&characterEncoding=utf-8
  datasource.username: root
  datasource.password: 12345.asdfg
  datasource.driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf.cache: false